version: "3"

tasks:
  transactions:
    cmds:
      - rye run dinero transactions

  rules:
    cmds:
      - rye run dinero rules

  dataset:
    cmds:
      - rye run dinero mkdataset

  fmt:
    ignore_error: true
    cmds:
      - rye run ruff --fix dinero
      - rye run black dinero
      - rye run isort dinero

  check:
    ignore_error: true
    cmds:
      - rye run ruff dinero
      - rye run black dinero --check
      - rye run isort dinero --check-only
